#!/bin/bash
BRANCHES_TO_SKIP=(master integration core_v3)
BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"
BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" "$1")

if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
  if [[ $BRANCH_NAME =~ (QC-[0-9]+)_ ]]; then
    BRANCH_NAME=${BASH_REMATCH[1]}
  fi
    sed -i.bak -e "1s/^/$BRANCH_NAME /" "$1"
fi